const assert=require("node:assert/strict");const {createBackup,validateBackup,mergeBackupData,SCHEMA_VERSION}=require("../public/catch-backup.js");const {getGermanFishName}=require("../backend/fish-localization");
(async()=>{
 const water={id:"water-iller",name:"Iller",type:"Fluss",region:"Allgäu",note:"Kalt",createdAt:"2026-09-03T10:00:00Z",updatedAt:"2026-09-03T11:00:00Z"};
 const imageBlob=new Blob([Uint8Array.from([1,2,3,4])],{type:"image/jpeg"}),location={latitude:47.98,longitude:10.15,accuracy:12,capturedAt:"2026-09-03T12:00:00.000Z"},identification={primarySpecies:"Hecht",primaryConfidence:.91,secondOpinionSpecies:"Hecht",consensusType:"agreement"};
 const caught={id:"catch-hecht",speciesName:"Hecht",scientificName:"Esox lucius",caughtDate:"2026-09-03",caughtTime:"10:00",lengthCm:80,weightGrams:3500,waterId:water.id,waterNameSnapshot:"Iller",waterName:"Iller",note:"Schilf",location,identification,imageBlob,apiKey:"DARF-NICHT-EXPORTIERT-WERDEN",providerConfig:{token:"secret"}};
 const backup=await createBackup([caught],[water],"0.5.0");assert.equal(backup.schemaVersion,SCHEMA_VERSION);assert.equal(backup.appVersion,"0.5.0");assert.deepEqual(backup.waters[0],water);assert.ok(backup.catches[0].image.startsWith("data:image/jpeg;base64,"));
 const restored=await validateBackup(backup),rc=restored.catches[0];assert.deepEqual(restored.waters[0],water);assert.equal(rc.id,caught.id);assert.equal(rc.waterId,water.id);assert.equal(rc.waterNameSnapshot,"Iller");assert.deepEqual(rc.location,location);assert.deepEqual(rc.identification,identification);assert.deepEqual([...new Uint8Array(await rc.imageBlob.arrayBuffer())],[1,2,3,4]);
 const empty=await validateBackup(await createBackup([],[],"0.5.0"));assert.deepEqual(empty.catches,[]);assert.deepEqual(empty.waters,[]);
 const legacy=await validateBackup({schemaVersion:1,appVersion:"0.4",exportedAt:new Date().toISOString(),catches:[{id:"old",speciesName:"Döbel",caughtDate:"2025-01-01",waterName:"Iller",image:null}]});assert.equal(legacy.waters.length,0);assert.equal(legacy.catches[0].waterId,null);assert.equal(legacy.catches[0].waterNameSnapshot,"Iller");assert.equal(legacy.catches[0].location,null);
 const local={waters:[{...water,name:"Lokal"}],catches:[{...caught,speciesName:"Lokal"}]},incoming={waters:[water,{...water,id:"water-b",name:"Bach"}],catches:[caught,{...caught,id:"catch-b",waterId:"water-b"}]},merged=mergeBackupData(local,incoming);assert.equal(merged.waters.length,2);assert.equal(merged.catches.length,2);assert.equal(merged.waters.find(x=>x.id===water.id).name,"Lokal");assert.equal(merged.catches.find(x=>x.id===caught.id).speciesName,"Lokal");assert.equal(merged.catches.find(x=>x.id==="catch-b").waterId,"water-b");
 const base={schemaVersion:2,appVersion:"0.5.0",exportedAt:new Date().toISOString(),catches:[],waters:[]};
 await assert.rejects(()=>validateBackup({...base,waters:[{...water,id:""}]}),/Gewässerdaten/);await assert.rejects(()=>validateBackup({...base,waters:[{...water,type:"Ozean"}]}),/Gewässerdaten/);
 for(const loc of [{...location,latitude:91},{...location,longitude:-181},{...location,accuracy:-1}])await assert.rejects(()=>validateBackup({...base,catches:[{...caught,image:null,location:loc}]}),/Standortdaten/);
 await assert.rejects(()=>validateBackup({...base,catches:[{...caught,image:"data:text/plain;base64,QQ=="}]}),/Fangfoto/);await assert.rejects(()=>validateBackup({...base,catches:[{...caught,caughtDate:"falsch",image:null}]}),/Fangdaten/);
 const orphan=await validateBackup({...base,catches:[{...caught,waterId:"missing",waterNameSnapshot:"Iller",image:null}]});assert.equal(orphan.catches[0].waterId,"missing");assert.equal(orphan.waters.length,0);
 assert.equal(JSON.stringify(backup).includes("DARF-NICHT-EXPORTIERT-WERDEN"),false);assert.equal(JSON.stringify(backup).includes("providerConfig"),false);assert.equal(JSON.stringify(backup).includes("process.env"),false);assert.equal(getGermanFishName("Anguilla rostrata"),"Amerikanischer Aal");assert.equal(getGermanFishName("Anguilla anguilla"),"Europäischer Aal");console.log("Fangbuch-Backup-Tests erfolgreich.");
})();
