const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{spawn,spawnSync}=require("node:child_process");const {createRateLimiter}=require("../backend/rate-limit");
(async()=>{
 const headers={};let forwarded=0,received;const limiter=createRateLimiter({windowMs:600000,maxRequests:2}),req={ip:"127.0.0.1"},res={set:(k,v)=>headers[k]=v},next=e=>{if(e)received=e;else forwarded++;};limiter(req,res,next);limiter(req,res,next);limiter(req,res,next);assert.equal(forwarded,2);assert.equal(received.status,429);assert.equal(received.message,"Zu viele Anfragen. Bitte versuche es in einigen Minuten erneut.");assert.ok(Number(headers["Retry-After"])>0);
 const root=path.resolve(__dirname,".."),env={...process.env,NODE_ENV:"production",APP_ENV:"beta",PORT:"3219",TRUST_PROXY:"1",PUBLIC_FEEDBACK_EMAIL:"feedback@example.test",FISHIAL_CLIENT_ID:"test",FISHIAL_CLIENT_SECRET:"test",SECOND_OPINION_ENABLED:"false",GEMINI_API_KEY:""};const child=spawn(process.execPath,["server.js"],{cwd:root,env,stdio:"ignore"});
 try{let health;for(let i=0;i<30;i++){try{health=await fetch("http://127.0.0.1:3219/api/health");break;}catch{await new Promise(r=>setTimeout(r,100));}}assert.ok(health);assert.deepEqual(await health.json(),{status:"ok",version:"0.6.2"});assert.equal(health.headers.get("x-content-type-options"),"nosniff");assert.equal(health.headers.get("x-frame-options"),"DENY");assert.match(health.headers.get("content-security-policy"),/default-src 'self'/);assert.equal((await fetch("http://127.0.0.1:3219/api/dev/stats")).status,404);assert.equal((await fetch("http://127.0.0.1:3219/api/dev/gemini-benchmark",{method:"POST"})).status,404);const optionsA={headers:{"x-forwarded-for":"203.0.113.10"}},optionsB={headers:{"x-forwarded-for":"203.0.113.11"}},networkA=await (await fetch("http://127.0.0.1:3219/api/beta/network-check",optionsA)).json(),networkA2=await (await fetch("http://127.0.0.1:3219/api/beta/network-check",optionsA)).json(),networkB=await (await fetch("http://127.0.0.1:3219/api/beta/network-check",optionsB)).json();assert.equal(networkA.proxyTrusted,true);assert.equal(networkA.forwardedForPresent,true);assert.match(networkA.clientIpHash,/^[a-f0-9]{16}$/);assert.equal(networkA.clientIpHash,networkA2.clientIpHash);assert.notEqual(networkA.clientIpHash,networkB.clientIpHash);assert.doesNotMatch(JSON.stringify(networkA),/203\.0\.113\.10/);const errorResponse=await fetch("http://127.0.0.1:3219/api/analyze",{method:"POST"}),body=await errorResponse.text();assert.equal(errorResponse.status,400);assert.doesNotMatch(body,/stack|ECONN|node_modules/i);}finally{child.kill();}
 const production=spawn(process.execPath,["server.js"],{cwd:root,env:{...env,APP_ENV:"production",PORT:"3220"},stdio:"ignore"});try{let response;for(let i=0;i<30;i++){try{response=await fetch("http://127.0.0.1:3220/api/beta/network-check");break;}catch{await new Promise(r=>setTimeout(r,100));}}assert.equal(response?.status,404);}finally{production.kill();}
 const missing=spawnSync(process.execPath,["-e","const c=require('./backend/config');c.validateStartup()"],{cwd:root,encoding:"utf8",env:{...process.env,NODE_ENV:"production",APP_ENV:"beta",FISHIAL_CLIENT_ID:"",FISHIAL_CLIENT_SECRET:"",GEMINI_API_KEY:"",SECOND_OPINION_ENABLED:"true",SECOND_OPINION_PROVIDER:"GEMINI"}});assert.notEqual(missing.status,0);assert.match(missing.stderr,/FISHIAL_CLIENT_ID/);
 const html=fs.readFileSync(path.join(root,"public","index.html"),"utf8"),worker=fs.readFileSync(path.join(root,"public","service-worker.js"),"utf8"),server=fs.readFileSync(path.join(root,"server.js"),"utf8"),client=fs.readFileSync(path.join(root,"public","app.js"),"utf8"),pkg=require("../package.json");assert.equal(pkg.version,"0.6.2");assert.match(pkg.engines.node,/20/);assert.match(html,/Private Beta · 0\.6\.2/);assert.match(html,/Diese Version befindet sich im Testbetrieb/);assert.match(html,/Datenschutz/);assert.match(html,/Impressum/);assert.match(html,/Feedback kopieren/);assert.match(worker,/shell-v12/);assert.match(worker,/caches\.delete\(key\)/);assert.doesNotMatch(worker,/indexedDB|imageBlob/);assert.match(server,/app\.listen\(config\.port, config\.host/);assert.match(server,/SIGTERM/);assert.match(server,/config\.appEnv === "beta"/);assert.match(server,/!config\.isProductionLike/);assert.doesNotMatch(html+client,/FISHIAL_CLIENT_SECRET|GEMINI_API_KEY/);for(const relative of ["/api/analyze","/api/species","/service-worker.js"])assert.ok(client.includes(`\"${relative}\"`)||html.includes(`\"${relative}\"`));
 console.log("Private-Beta-Tests erfolgreich.");
})().catch(e=>{console.error(e);process.exitCode=1;});
