const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const {normalizeWeightInput,weightInputFromGrams,formatWeight,normalizeStoredRecord}=require("../public/catch-store.js");
const {MemoryLocalBackupStore}=require("../public/local-backup-store.js");
const {createBackup,validateBackup}=require("../public/catch-backup.js");
(async()=>{
 assert.equal(normalizeWeightInput("13","kg"),13000);assert.equal(normalizeWeightInput("3,25","kg"),3250);assert.equal(normalizeWeightInput("3.25","kg"),3250);assert.equal(normalizeWeightInput("850","g"),850);assert.equal(normalizeWeightInput("","kg"),null);assert.throws(()=>normalizeWeightInput("-1","kg"));assert.throws(()=>normalizeWeightInput("abc","kg"));
 assert.deepEqual(weightInputFromGrams(13000),{value:"13",unit:"kg"});assert.deepEqual(weightInputFromGrams(850),{value:"850",unit:"g"});assert.equal(normalizeStoredRecord({weightKg:3.002}).weightGrams,3002);assert.equal(formatWeight(850),"850 g");assert.equal(formatWeight(1250),"1,25 kg");assert.equal(formatWeight(13000),"13 kg");
 const store=new MemoryLocalBackupStore();assert.equal(await store.get(),null);const water={id:"w",name:"Iller",type:"Fluss",region:"",note:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const imageBlob=new Blob([Uint8Array.of(7)],{type:"image/jpeg"});const identification={primarySpecies:"Hecht"},location={latitude:48,longitude:10,accuracy:5,capturedAt:new Date().toISOString()};const first=await createBackup([{id:"c",speciesName:"Hecht",caughtDate:"2026-09-04",weightGrams:13000,waterId:"w",waterNameSnapshot:"Iller",imageBlob,identification,location,secret:"no"}],[water],"0.5.1");const saved=await store.save(first);assert.ok(saved.createdAt);let loaded=await store.get();let validated=await validateBackup(loaded.backup);assert.equal(validated.waters[0].name,"Iller");assert.deepEqual(validated.catches[0].location,location);assert.deepEqual(validated.catches[0].identification,identification);assert.equal((await validated.catches[0].imageBlob.arrayBuffer()).byteLength,1);assert.doesNotMatch(JSON.stringify(loaded),/secret/);
 const second=await createBackup([],[],"0.5.1");await store.save(second);loaded=await store.get();assert.equal(loaded.backup.catches.length,0,"Nur die letzte lokale Sicherung bleibt erhalten");
 const html=fs.readFileSync(path.join(__dirname,"..","public","index.html"),"utf8"),worker=fs.readFileSync(path.join(__dirname,"..","public","service-worker.js"),"utf8"),catchSource=fs.readFileSync(path.join(__dirname,"..","public","catch-store.js"),"utf8");assert.match(html,/Letztes Backup wiederherstellen/);assert.match(html,/name="weightUnit"/);assert.match(worker,/fish-identifier-shell-v11/);assert.match(worker,/local-backup-store\.js/);assert.match(catchSource,/indexedDB\.open\(DB_NAME, 3\)/);
 console.log("UX-Polish-Tests erfolgreich.");
})();
